// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwmezuoxrvifkzcaiipl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53bWV6dW94cnZpZmt6Y2FpaXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTg5MzcsImV4cCI6MjA2Mzc5NDkzN30.1wQUP7XNipORtU5NKqI4ZyE58AgK7AWlWAczh8r0ai4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);